---
title: "How the pineapple connects the South to the North in Hawaii"
author: "MK Lau"
date: 12June2018
categories: ["foodways"]
tags: ["pineapple", "history", "Hawaii", "hospitality", "imperialism", "expansionism"]
---

## Pineapple Casserole at a Southern Funeral

## Pacific Imperialism

## Characteristics, Ecology, History

- Bromeliad
- Native to South America
- Scientific name is derived from a native word for tasty fruit
- Transported by natives to the Carribean
- Encountered by Cristopher Columbus
- Hospitality: Rareity and association with returning seamen

## Sugar and Other Foods for Colonization

- New England missionaries and entrepreneurs
- Hospitality foods to re-inforce invasion
- James Hunnewell
- Peter Cushman Jones
- Sanford Dole

## Colonial Foods become Imperial Foods

- Hawaiian League
- Teddy Roosevelt
- Henry Cabot Lodge

## The Quest for Annexation

- Bayonet Treaty
- New Lands Resolution
- Hawaiian Organic Act
- Annexation
- Statehood

## Imperial Foods become Industrial Foods

- James D Dole
- C&H
- The Big Five Hawaii Companies
- Matson Shipping

## US "Apologies" and the Rights of the Disenfranchised

- 1988 Civil Liberties Act - Japanese Internment (Reagan)
- 1993 Hawaiian Apology Resolution (Clinton)
- 1997 Tuskegee Experiment (Clinton)
- 2008 Slavery Jim Crow Laws Apology Resolution (Obama)
- Apologies explicitely written to not have legal impact
- David Akaka (Senator Hawaii, Deceased Apr 6 2018)

## James H Blount: An Unlikely Ally of 

- Blount Report
- "Freedom does not necessarily mean freedom from alien domination,
bot unly a change of masters deemed by the new master beneficial to
the 'slave'." JH Blount *The American Occupation of the Phillipines*

## Other Foods Common between the South and Hawaii

- Pig roast
- Sweet potato
- Greens (Taro, Poke, Collards, Mustards)

## Southern Sugar and Pineapple Production

- American Sugar Refining
- Connection to African Slave Trade?
- Plantations: Southern and Hawaiian

## Dealing with the Past

- History Washing
- Cultural appropriation
- Healing the Soul Wound

## Rolling Back Human Rights and Dignity

- Bearsears National Monument
- Keystone XL pipeline
- Immigrants now face similar to the struggles of first-peoples and
the decedents of "freedmen" with reduced protections and
acknowledgement of inequalities
- What happens when your rights exist outside the law?
