---
title: "How the pineapple connects the South to the North in Hawaii"
author: "MK Lau"
date: 12June2018
categories: ["foodways"]
tags: ["pineapple", "history", "Hawaii", "hospitality", "imperialism", "expansionism"]
---

## Pineapple Casserole at a Southern Funeral

## Pacific Imperialism

## Characteristics, Ecology, History

- Bromeliad
- Native to South America
- Scientific name is derived from a native word for tasty fruit
- Transported by natives to the Carribean
- Encountered by Cristopher Columbus
- Hospitality: Rareity and association with returning seamen

## Sugar and Other Foods for Colonization

- New England missionaries and entrepreneurs
- Hospitality foods to re-inforce invasion
- James Hunnewell
- Peter Cushman Jones
- Sanford Dole

## Colonial Foods become Imperial Foods

- Hawaiian League
- Teddy Roosevelt
- Henry Cabot Lodge
- 

## Imperial Foods become Industrial Foods

- James D Dole
- C&H
- The Big Five Hawaii Companies
- Matson Shipping

## Modern Movement for First People's Rights

- Bearsears National Monument
- 

## Other Foods Common between the South and Hawaii

- Pig roast
- Sweet potato
- Greens (Taro, Poke, Collards, Mustards)

## Southern Sugar and Pineapple Production

- American Sugar Refining
- Connection to African Slave Trade?
- Plantations: Southern and Hawaiian

## Dealing with the Past

- History Washing
- Cultural appropriation
- Healing the Soul Wound
